const codes = [
  {'value': 'af', 'text': 'Afrikaans'},
  {'value': 'sq', 'text': 'Albanian'},
  {'value': 'ar', 'text': 'Arabic (Standard)'},
  {'value': 'ar-dz', 'text': 'Arabic (Algeria)'},
  {'value': 'ar-bh', 'text': 'Arabic (Bahrain)'},
  {'value': 'ar-eg', 'text': 'Arabic (Egypt)'},
  {'value': 'ar-iq', 'text': 'Arabic (Iraq)'},
  {'value': 'ar-jo', 'text': 'Arabic (Jordan)'},
  {'value': 'ar-kw', 'text': 'Arabic (Kuwait)'},
  {'value': 'ar-lb', 'text': 'Arabic (Lebanon)'},
  {'value': 'ar-ly', 'text': 'Arabic (Libya)'},
  {'value': 'ar-ma', 'text': 'Arabic (Morocco)'},
  {'value': 'ar-om', 'text': 'Arabic (Oman)'},
  {'value': 'ar-qa', 'text': 'Arabic (Qatar)'},
  {'value': 'ar-sa', 'text': 'Arabic (Saudi Arabia)'},
  {'value': 'ar-sy', 'text': 'Arabic (Syria)'},
  {'value': 'ar-tn', 'text': 'Arabic (Tunisia)'},
  {'value': 'ar-ae', 'text': 'Arabic (U.A.E.)'},
  {'value': 'ar-ye', 'text': 'Arabic (Yemen)'},
  {'value': 'an', 'text': 'Aragonese'},
  {'value': 'hy', 'text': 'Armenian'},
  {'value': 'as', 'text': 'Assamese'},
  {'value': 'ast', 'text': 'Asturian'},
  {'value': 'az', 'text': 'Azerbaijani'},
  {'value': 'eu', 'text': 'Basque'},
  {'value': 'be', 'text': 'Belarusian'},
  {'value': 'bn', 'text': 'Bengali'},
  {'value': 'bs', 'text': 'Bosnian'},
  {'value': 'br', 'text': 'Breton'},
  {'value': 'bg', 'text': 'Bulgarian'},
  {'value': 'my', 'text': 'Burmese'},
  {'value': 'ca', 'text': 'Catalan'},
  {'value': 'ch', 'text': 'Chamorro'},
  {'value': 'ce', 'text': 'Chechen'},
  {'value': 'zh', 'text': 'Chinese'},
  {'value': 'zh-hk', 'text': 'Chinese (Hong Kong)'},
  {'value': 'zh-cn', 'text': 'Chinese (PRC)'},
  {'value': 'zh-sg', 'text': 'Chinese (Singapore)'},
  {'value': 'zh-tw', 'text': 'Chinese (Taiwan)'},
  {'value': 'cv', 'text': 'Chuvash'},
  {'value': 'co', 'text': 'Corsican'},
  {'value': 'cr', 'text': 'Cree'},
  {'value': 'hr', 'text': 'Croatian'},
  {'value': 'cs', 'text': 'Czech'},
  {'value': 'da', 'text': 'Danish'},
  {'value': 'nl', 'text': 'Dutch (Standard)'},
  {'value': 'nl-be', 'text': 'Dutch (Belgian)'},
  {'value': 'en', 'text': 'English'},
  {'value': 'en-au', 'text': 'English (Australia)'},
  {'value': 'en-bz', 'text': 'English (Belize)'},
  {'value': 'en-ca', 'text': 'English (Canada)'},
  {'value': 'en-ie', 'text': 'English (Ireland)'},
  {'value': 'en-jm', 'text': 'English (Jamaica)'},
  {'value': 'en-nz', 'text': 'English (New Zealand)'},
  {'value': 'en-ph', 'text': 'English (Philippines)'},
  {'value': 'en-za', 'text': 'English (South Africa)'},
  {'value': 'en-tt', 'text': 'English (Trinidad & Tobago)'},
  {'value': 'en-gb', 'text': 'English (United Kingdom)'},
  {'value': 'en-us', 'text': 'English (United States)'},
  {'value': 'en-zw', 'text': 'English (Zimbabwe)'},
  {'value': 'eo', 'text': 'Esperanto'},
  {'value': 'et', 'text': 'Estonian'},
  {'value': 'fo', 'text': 'Faeroese'},
  {'value': 'fa', 'text': 'Farsi'},
  {'value': 'fj', 'text': 'Fijian'},
  {'value': 'fi', 'text': 'Finnish'},
  {'value': 'fr', 'text': 'French (Standard)'},
  {'value': 'fr-be', 'text': 'French (Belgium)'},
  {'value': 'fr-ca', 'text': 'French (Canada)'},
  {'value': 'fr-fr', 'text': 'French (France)'},
  {'value': 'fr-lu', 'text': 'French (Luxembourg)'},
  {'value': 'fr-mc', 'text': 'French (Monaco)'},
  {'value': 'fr-ch', 'text': 'French (Switzerland)'},
  {'value': 'fy', 'text': 'Frisian'},
  {'value': 'fur', 'text': 'Friulian'},
  {'value': 'gd', 'text': 'Gaelic (Scots)'},
  {'value': 'gd-ie', 'text': 'Gaelic (Irish)'},
  {'value': 'gl', 'text': 'Galacian'},
  {'value': 'ka', 'text': 'Georgian'},
  {'value': 'de', 'text': 'German (Standard)'},
  {'value': 'de-at', 'text': 'German (Austria)'},
  {'value': 'de-de', 'text': 'German (Germany)'},
  {'value': 'de-li', 'text': 'German (Liechtenstein)'},
  {'value': 'de-lu', 'text': 'German (Luxembourg)'},
  {'value': 'de-ch', 'text': 'German (Switzerland)'},
  {'value': 'el', 'text': 'Greek'},
  {'value': 'gu', 'text': 'Gujurati'},
  {'value': 'ht', 'text': 'Haitian'},
  {'value': 'he', 'text': 'Hebrew'},
  {'value': 'hi', 'text': 'Hindi'},
  {'value': 'hu', 'text': 'Hungarian'},
  {'value': 'is', 'text': 'Icelandic'},
  {'value': 'id', 'text': 'Indonesian'},
  {'value': 'iu', 'text': 'Inuktitut'},
  {'value': 'ga', 'text': 'Irish'},
  {'value': 'it', 'text': 'Italian (Standard)'},
  {'value': 'it-ch', 'text': 'Italian (Switzerland)'},
  {'value': 'ja', 'text': 'Japanese'},
  {'value': 'kn', 'text': 'Kannada'},
  {'value': 'ks', 'text': 'Kashmiri'},
  {'value': 'kk', 'text': 'Kazakh'},
  {'value': 'km', 'text': 'Khmer'},
  {'value': 'ky', 'text': 'Kirghiz'},
  {'value': 'tlh', 'text': 'Klingon'},
  {'value': 'ko', 'text': 'Korean'},
  {'value': 'ko-kp', 'text': 'Korean (North Korea)'},
  {'value': 'ko-kr', 'text': 'Korean (South Korea)'},
  {'value': 'la', 'text': 'Latin'},
  {'value': 'lv', 'text': 'Latvian'},
  {'value': 'lt', 'text': 'Lithuanian'},
  {'value': 'lb', 'text': 'Luxembourgish'},
  {'value': 'mk', 'text': 'FYRO Macedonian'},
  {'value': 'ms', 'text': 'Malay'},
  {'value': 'ml', 'text': 'Malayalam'},
  {'value': 'mt', 'text': 'Maltese'},
  {'value': 'mi', 'text': 'Maori'},
  {'value': 'mr', 'text': 'Marathi'},
  {'value': 'mo', 'text': 'Moldavian'},
  {'value': 'nv', 'text': 'Navajo'},
  {'value': 'ng', 'text': 'Ndonga'},
  {'value': 'ne', 'text': 'Nepali'},
  {'value': 'no', 'text': 'Norwegian'},
  {'value': 'nb', 'text': 'Norwegian (Bokmal)'},
  {'value': 'nn', 'text': 'Norwegian (Nynorsk)'},
  {'value': 'oc', 'text': 'Occitan'},
  {'value': 'or', 'text': 'Oriya'},
  {'value': 'om', 'text': 'Oromo'},
  {'value': 'fa-ir', 'text': 'Persian/Iran'},
  {'value': 'pl', 'text': 'Polish'},
  {'value': 'pt', 'text': 'Portuguese'},
  {'value': 'pt-br', 'text': 'Portuguese (Brazil)'},
  {'value': 'pa', 'text': 'Punjabi'},
  {'value': 'pa-in', 'text': 'Punjabi (India)'},
  {'value': 'pa-pk', 'text': 'Punjabi (Pakistan)'},
  {'value': 'qu', 'text': 'Quechua'},
  {'value': 'rm', 'text': 'Rhaeto-Romanic'},
  {'value': 'ro', 'text': 'Romanian'},
  {'value': 'ro-mo', 'text': 'Romanian (Moldavia)'},
  {'value': 'ru', 'text': 'Russian'},
  {'value': 'ru-mo', 'text': 'Russian (Moldavia)'},
  {'value': 'sz', 'text': 'Sami (Lappish)'},
  {'value': 'sg', 'text': 'Sango'},
  {'value': 'sa', 'text': 'Sanskrit'},
  {'value': 'sc', 'text': 'Sardinian'},
  {'value': 'sd', 'text': 'Sindhi'},
  {'value': 'si', 'text': 'Singhalese'},
  {'value': 'sr', 'text': 'Serbian'},
  {'value': 'sk', 'text': 'Slovak'},
  {'value': 'sl', 'text': 'Slovenian'},
  {'value': 'so', 'text': 'Somani'},
  {'value': 'sb', 'text': 'Sorbian'},
  {'value': 'es', 'text': 'Spanish'},
  {'value': 'es-ar', 'text': 'Spanish (Argentina)'},
  {'value': 'es-bo', 'text': 'Spanish (Bolivia)'},
  {'value': 'es-cl', 'text': 'Spanish (Chile)'},
  {'value': 'es-co', 'text': 'Spanish (Colombia)'},
  {'value': 'es-cr', 'text': 'Spanish (Costa Rica)'},
  {'value': 'es-do', 'text': 'Spanish (Dominican Republic)'},
  {'value': 'es-ec', 'text': 'Spanish (Ecuador)'},
  {'value': 'es-sv', 'text': 'Spanish (El Salvador)'},
  {'value': 'es-gt', 'text': 'Spanish (Guatemala)'},
  {'value': 'es-hn', 'text': 'Spanish (Honduras)'},
  {'value': 'es-mx', 'text': 'Spanish (Mexico)'},
  {'value': 'es-ni', 'text': 'Spanish (Nicaragua)'},
  {'value': 'es-pa', 'text': 'Spanish (Panama)'},
  {'value': 'es-py', 'text': 'Spanish (Paraguay)'},
  {'value': 'es-pe', 'text': 'Spanish (Peru)'},
  {'value': 'es-pr', 'text': 'Spanish (Puerto Rico)'},
  {'value': 'es-es', 'text': 'Spanish (Spain)'},
  {'value': 'es-uy', 'text': 'Spanish (Uruguay)'},
  {'value': 'es-ve', 'text': 'Spanish (Venezuela)'},
  {'value': 'sx', 'text': 'Sutu'},
  {'value': 'sw', 'text': 'Swahili'},
  {'value': 'sv', 'text': 'Swedish'},
  {'value': 'sv-fi', 'text': 'Swedish (Finland)'},
  {'value': 'sv-sv', 'text': 'Swedish (Sweden)'},
  {'value': 'ta', 'text': 'Tamil'},
  {'value': 'tt', 'text': 'Tatar'},
  {'value': 'te', 'text': 'Teluga'},
  {'value': 'th', 'text': 'Thai'},
  {'value': 'tig', 'text': 'Tigre'},
  {'value': 'ts', 'text': 'Tsonga'},
  {'value': 'tn', 'text': 'Tswana'},
  {'value': 'tr', 'text': 'Turkish'},
  {'value': 'tk', 'text': 'Turkmen'},
  {'value': 'uk', 'text': 'Ukrainian'},
  {'value': 'hsb', 'text': 'Upper Sorbian'},
  {'value': 'ur', 'text': 'Urdu'},
  {'value': 've', 'text': 'Venda'},
  {'value': 'vi', 'text': 'Vietnamese'},
  {'value': 'vo', 'text': 'Volapuk'},
  {'value': 'wa', 'text': 'Walloon'},
  {'value': 'cy', 'text': 'Welsh'},
  {'value': 'xh', 'text': 'Xhosa'},
  {'value': 'ji', 'text': 'Yiddish'},
  {'value': 'zu', 'text': 'Zulu'}
]
export default codes
